server:
  port: ${SERVER_PORT:8081}

sprintwise:
  gtfs:
    feeds:
      - id: mta
        path: ${SPRINTWISE_MTA_GTFS_PATH:../data/gtfs/mta}
        enabled: ${SPRINTWISE_MTA_GTFS_ENABLED:true}
      - id: lirr
        path: ${SPRINTWISE_LIRR_GTFS_PATH:../data/gtfs/lirr}
        enabled: ${SPRINTWISE_LIRR_GTFS_ENABLED:true}
